Repository mgacrama211176/katiwala, pull requests merged in 2024-02, with the labels that each got.

#15 Issue#14 upload documents
  eas.json
  package.json
  screens/Global components/FileUploadCardComponent.jsx
  screens/Register/FaceVerify.jsx
  screens/Register/FileUploadCapture.jsx
  screens/Register/index.jsx
  yarn.lock
Labels: Feature

#24 Issue#11--Issue#21--Solution Done
  App.js
  screens/Login/index.jsx
Labels: enhancement

#9 merge request
  package.json
  screens/Register/index.jsx
  yarn.lock
Labels: help wanted

#27 22 bug dob UI bug
  screens/Register/index.jsx
Labels: bug, Feature
