Repository mgacrama211176/katiwala, pull requests merged in 2024-03, with the labels that each got.

#28 password validation
  package.json
  recoil/NewUserAtom.js
  screens/Global components/GlobalButtons.jsx
  screens/Register/index.jsx
  screens/Register/styles.js
Labels: bug

#23 Updated UI for RateGenerator
  screens/Global components/EstimateCard.jsx
Labels: enhancement, Feature

#29 Enhancement refactor and fix routes and added all gathered date on recoil
  package.json
  recoil/NewUserAtom.js
  screens/Global components/FileUploadCardComponent.jsx
  screens/Global components/GlobalButtons.jsx
  screens/Login/index.jsx
  screens/Register/FaceVerify.jsx
  screens/Register/FileUploadCapture.jsx
  screens/Register/RateGenerator.jsx
  screens/Register/index.jsx
  yarn.lock
Labels: enhancement

#32 UI Feature: Privacy Policy Screen resubmission lol
  App.js
  screens/Policies/PrivacyPolicy.jsx
  screens/Policies/TermsOfService.jsx
  screens/Policies/privacy-policy-contents.js
  screens/Policies/styles/privacy-policy-styles.js
  screens/Register/index.jsx
Labels: Feature
